title: 모비랩(Mobilab)
email: mobione@mobidays.com
description: |
  세상 모든 트래픽의 가장 효율적인 연결.
  Mobidays의 기술 블로그 mobilab입니다.
baseurl: ''
url: 'https://mobilab.mobidays.com'
timezone: Asia/Seoul
reply: false

repository:  mobidays-dev/mobilab

permalink: /:year/:month/:day/:slug/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

# plugins:
plugins_dir:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    # source: _data/authors.yml
    output: true
    permalink: /authors/:path/
    # permalink: /authors/:slug/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, static]
github: [metadata]

author: mobione@mobidays.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets

# google_analytics:
#  ua: 'UA-72007721-1'
facebook:
  app_id: '2103909196517733'
kakao:
  app_key : '6f032c9f8925f03d4b23e8a9058837b1'
twitter:
  username:
google_plus:
  username: mobidev
naver_blog:
  username: mobidev
