[[redirects]]
  from = "https://mobidays-dev.netlify.com/*"
  to = "https://mobilab.mobidays.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://mobilab.mobidays.com/mainlist"
  to = "https://mobilab.mobidays.com"
  status = 301
  force = true
