backend:
  name: github
  repo: mobidays-dev/mobidays-dev.github.io
  branch: master
  site_domain: mobitest.netlify.com

# publish_mode: editorial_workflow
display_url: https://mobitest.netlify.com/
media_folder: "static/images"
# public_folder: "/public/"


collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "제목", name: "title", widget: "string"}
      - label: "작성자"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name", "title"]
        valueField: "name"
        displayFields: ["name", "title"]
      #- {label: "작성자", name: "author", widget: "string"}
      #- label : "작성자"
      #  name : "author"
      #  folder: "_auhors" # The path to the folder where the documents are stored
      #  widget: "list"
      #      - {label: "작성자", name: "author", widget: "string" }
      - {label: "작성일자", name: "date", widget: "datetime" , format: "YYYY-MM-DD hh:mm"}
      - {label: "커버이미지", name: "image", widget: "image", required: false }
      - label: "태그테스트"
        name: "testimonials"
        widget: "list"
        allow_add: true
        required: false
        field:
        - label: "작성자"
          name: "test"
          widget: "relation"
          collection: "authors"
          searchFields: ["name", "title"]
          valueField: "name"
      - label: "태그"
        name: "tags"
        widget: "list"
        allow_add: true
        required: false
        default: []
      # - {label: "태그", name: "tags", widget: "string", required: false }
      - {label: "노출여부", name: "published", widget: "boolean", default: false }
      - {label: "포스트", name: "body", widget: "markdown"}
    #meta:
    #  - {label: "SEO Description", name: "description", widget: "text"}
- label: "Profile"
  name: "profile"
  widget: "object"
  fields:
    - {label: "Public", name: "public", widget: "boolean", default: true}
    - {label: "Name", name: "name", widget: "string"}
    - label: "Birthdate"
      name: "birthdate"
      widget: "date"
      default: ""
      format: "MM/DD/YYYY"
    - label: "Address"
      name: "address"
      widget: "object"
      fields:
        - {label: "Street Address", name: "street", widget: "string"}
        - {label: "City", name: "city", widget: "string"}
        - {label: "Postal Code", name: "post-code", widget: "string"}
  - name: "authors" # Used in routes, e.g. /admin/collections/blog
    label: "Authors" # Used in the UI
    label_singular: "Author" # Used in the UI, ie: "New Post"
    folder: "_authors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "닉네임", name: "name", widget: "string"}
      - {label: "이름", name: "title", widget: "string", required: false }
      - {label: "이메일", name: "email", widget: "string",  required: false }
      - {label: "짧은 소개", name: "desc", widget: "text",  required: false }
      - {label: "아바타", name: "image", widget: "image", default: "/static/authors/default.png"}

  #- name: "settings"
  #  label: "Settings"
  #  delete: false # Prevent users from deleting documents in this collection
  #  editor:
  #    preview: false
  #  files:
  #    - name: "general"
  #      label: "Site Settings"
  #      file: "_data/settings.json"
  #      description: "General Site Settings"
  #      fields:
  #        - {label: "Global title", name: "site_title", widget: "string"}
  #        - label: "Post Settings"
  #          name: posts
  #          widget: "object"
  #          fields:
  #            - {label: "Number of posts on frontpage", name: front_limit, widget: number}
  #            - {label: "Default Author", name: author, widget: string}
  #            - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}
#
#      - name: "authors"
#        label: "Authors"
#        file: "_data/authors.yml"
#        description: "Author descriptions"
#        fields:
#          - name: authors
#            label: Authors
#            label_singular: "Author"
#            widget: list
#            fields:
#              - {label: "Name", name: "name", widget: "string"}
#              - {label: "Description", name: "description", widget: "markdown"}
