backend:
  name: github
  repo: mobidays-dev/mobidays-dev.github.io
  branch: master
  site_domain: lab.mobidays.com

# publish_mode: editorial_workflow
display_url: https://lab.mobidays.com
media_folder: "static/images"
# public_folder: "/public/"

collections:
  - name: "drafts" # Used in routes, e.g. /admin/collections/blog
    label: "Draft" # Used in the UI
    label_singular: "Draft" # Used in the UI, ie: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    filter:
      field: "published"
      value: false
    description: >
      드래프트로 일단 글을 작성하고 [publish] 버튼으로 저장하세요 :)
      글을 완성하셨다면 노출여부를 ON으로 변경하면 즉시 글이 노출됩니다.
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "제목", name: "title", widget: "string"}
      - label: "작성자"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["title", "name"]
        valueField: "title"
        displayFields: ["title", "name"]
        default: "dev"
      - {label: "작성일", name: "date", widget: "datetime" , format: "YYYY-MM-DD hh:mm", dateFormat:true}
      - {label: "커버이미지 ", name: "image", widget: "image", required: false }
      - label: "커버이미지 출처"
        name: "cover"
        widget: "object"
        fields:
            - {label: "이미지 출처", name: "title", widget: "string", required: false }
            - {label: "이미지 출처 URL", name: "link", widget: "string", required: false }
        required: false
      - label: "태그"
        name: "tags"
        widget: "relation"
        collection: "tags"
        searchFields: [title]
        valueField: "title"
        displayFields: ["title"]
        multiple: true
        required: false
      - {label: "노출여부", name: "published", widget: "boolean", default: false }
      - {label: "포스트", name: "body", widget: "markdown"}

  - name: "posts" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    filter:
      field: "published"
      value: true
    description: >
      모비랩에 노출된 글을 확인하고 수정할 수 있습니다.
      새 글 작성은 Draft를 먼저 이용해 주세요.
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "제목", name: "title", widget: "string"}
      - label: "작성자"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["title", "name"]
        valueField: "title"
        displayFields: ["title", "name"]
        default: "dev"
      - {label: "작성일", name: "date", widget: "datetime" , format: "YYYY-MM-DD hh:mm", dateFormat:true}
      - {label: "커버이미지", name: "image", widget: "image", required: false }
      - label: "커버이미지 출처"
        name: "cover"
        widget: "object"
        fields:
            - {label: "이미지 출처", name: "title", widget: "string", required: false }
            - {label: "이미지 출처 URL", name: "link", widget: "string", required: false }
        required: false
      - label: "태그"
        name: "tags"
        widget: "relation"
        collection: "tags"
        searchFields: [title]
        valueField: "title"
        displayFields: ["title"]
        multiple: true
        required: false
      - {label: "노출여부", name: "published", widget: "boolean", default: true }
      - {label: "포스트", name: "body", widget: "markdown"}
    #meta:
    #  - {label: "SEO Description", name: "description", widget: "text"}

  - name: "authors" # Used in routes, e.g. /admin/collections/blog
    label: "Authors" # Used in the UI
    label_singular: "Author" # Used in the UI, ie: "New Post"
    folder: "_authors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    media_folder: "static/authors"
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "닉네임", name: "title", widget: "string"}
      - {label: "이름", name: "name", widget: "string", required: false }
      - {label: "이메일", name: "email", widget: "string",  required: false }
      - {label: "짧은 소개", name: "desc", widget: "string",  required: false }
      - {label: "썸네일 주소", name: "image", widget: "string", default: "/static/authors/default.png"}

  - name: "tags" # Used in routes, e.g. /admin/collections/blog
    label: "Tag" # Used in the UI
    label_singular: "Tag" # Used in the UI, ie: "New Post"
    folder: "_tags" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "태그명", name: "title", widget: "string"}
      - {label: "태그설명", name: "name", widget: "text", required: false }
