backend:
  name: github
  repo: 'mobidays-dev/mobidays-dev.github.io'
  branch: master
  site_domain: mobidays-dev.netlify.com

publish_mode: editorial_workflow
display_url: https://mobidays-dev.netlify.com/
media_folder: "static/images"
# public_folder: "/public/"


collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    filter:
      field: "published"
      value: true
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "제목", name: "title", widget: "string"}
      - label: "작성자"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name", "title"]
        valueField: "name"
        displayFields: ["name", "title"]
        default: "dev"
      - {label: "작성일자", name: "date", widget: "datetime" , format: "YYYY-MM-DD hh:mm"}
      - {label: "커버이미지", name: "image", widget: "image", required: false }
      - label: "커버이미지 출처 (필요시)"
        name: "cover"
        widget: "object"
        fields:
            - {label: "이미지 출처", name: "title", widget: "string", required: false }
            - {label: "이미지 출처 URL", name: "link", widget: "string", required: false }
        required: false
      - label: "태그"
        name: "tags"
        widget: "list"
        allow_add: true
        required: false
        # default: []
      - {label: "노출여부", name: "published", widget: "boolean", default: true }
      - {label: "포스트", name: "body", widget: "markdown"}
    #meta:
    #  - {label: "SEO Description", name: "description", widget: "text"}

  - name: "drafts" # Used in routes, e.g. /admin/collections/blog
    label: "Draft" # Used in the UI
    label_singular: "Draft" # Used in the UI, ie: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    filter:
      field: "published"
      value: false
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "제목", name: "title", widget: "string"}
      - label: "작성자"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name", "title"]
        valueField: "name"
        displayFields: ["name", "title"]
        default: "dev"
      - {label: "작성일자", name: "date", widget: "datetime" , format: "YYYY-MM-DD hh:mm"}
      - {label: "커버이미지", name: "image", widget: "image", required: false }
      - label: "커버이미지 출처 (필요시)"
        name: "cover"
        widget: "object"
        fields:
            - {label: "이미지 출처", name: "title", widget: "string", required: false }
            - {label: "이미지 출처 URL", name: "link", widget: "string", required: false }
        required: false
      - label: "태그"
        name: "tags"
        widget: "list"
        allow_add: true
        required: false
        # default: []
      - {label: "노출여부", name: "published", widget: "boolean", default: false }
      - {label: "포스트", name: "body", widget: "markdown"}
